# This is a templated file and must be kept up-to-date with the original
# from upstream at https://github.com/canonical/se-tooling-ci-common.
[tox]
envlist = py3,pep8,pylint
minversion = 4.50.0

[flake8]
enable-extensions = H106,H203,H204,H205,H904
show-source = true
exclude = ./.*,build,dist
import-order-style = pep8

[testenv]
basepython = {env:TOX_PYTHON:python3}
unit_tests = {toxinidir}/tests/unit/
pyfiles =
    {toxinidir}/setup.py \
    {toxinidir}/sru_lint \
    {[testenv]unit_tests}
deps =
    -r{toxinidir}/test-requirements.txt
commands =
    poetry run python -m unittest discover -s {[testenv]tests} {posargs}

[testenv:pep8]
commands = flake8 -v {posargs:{[testenv]pyfiles}}

[testenv:pylint]
commands = pylint -v --rcfile={toxinidir}/pylintrc {posargs:{[testenv]pyfiles}}

